### ISSUE TITLE
Add a changelog to track the change between versions

### ISSUE THREAD

**Issue by ahocquard** [donatj/mock-webserver#17]
Hello,

Would it be possible to provide a CHANGELOG.md in order to facilitate the migration between the versions please?

Thanks!

**Comment by donatj** [comment]
Are you looking for something more than is on the release notes?

https://github.com/donatj/mock-webserver/releases

**Comment by ahocquard** [comment]
Hello,

No, it seems perfect (my bad, I usually take a look at the changelog file instead of the release note of github).

Thanks, problem solved.
