### ISSUE TITLE
Server gets freezed when debugging

### ISSUE THREAD

**Issue by javierseixas** [donatj/mock-webserver#20]
Hi, I'm looking forward to been able to test with mock-webserver.

When I debug (I use xDebug) an script that has a request to the `MockWebServer`, I don't get any response, and the script gets stuck. My hypothesis is that when debugging, the new php process for the server also becomes debugged, and stays waiting for continuing.

The same script works as expected when I'm not debugging. I'm using the scripts sampled in the documentation.

Is there any way to make it debuggable?

Thanks!

**Comment by javierseixas** [comment]
After some investigation, I've seen that the `MockWebServer` creates a new process, and this new php process inheritance php configuration. This includes xdebug configuration.

Doing some testing, and changing `MockWebServer`, changing `idekey` in xdebug solves the problem. Looks like this:

```
$cmd    = "export XDEBUG_CONFIG='idekey=mock' && php -S {$this->host}:{$this->port} " . escapeshellarg($script);
```

However, it arises a problem. In the `MockWebServer`, bellow of generating the `$cmd` value, a new variable `$fullCmd`, in which `$cmd` is wrapped by `escapeshellcmd()` function.

It escapes `&&` to `\&\&` and make the `exec()` fail.

Here I'm a bit stuck, since I don't know a way to export that new config, but compatible with `escapeshellcmd()`.

**Comment by donatj** [comment]
On long reflection, I think I'd call this a local  environment problem and outside the scope.
