### ISSUE TITLE
Add support for variance by HTTP verb 

### ISSUE THREAD

**Issue by BramRoets** [donatj/mock-webserver#3]
Is it possible to add support for the HTTP verb ?

Something like: 

`        $server->setResponseOfPath(
            '/api/v1/users/5',
            '[user object]',
            [],
            200,
            'PUT'
        );`

**Comment by donatj** [comment]
@BramRoets Such that it *only* responds to that verb, or?

**Comment by donatj** [comment]
That should be doable in the near future.

In the meantime you can change the expected response of a path by calling `setResponseOfPath` more than once if that's a possibility for your code.

**Comment by BramRoets** [comment]
That it would only respond to this verb. I'm doing a get and put request to the same url but expect different responses. Thanks for the tip about setResponseOfPath

**Comment by dezmound** [comment]
Simple solution is change this line in `RequestInfo` class:
```php
$this->parsedUri = parse_url($server['REQUEST_URI']);
```
like this:
```php
$this->parsedUri = parse_url($server['REQUEST_URI'] . '.' . $server['REQUEST_METHOD']);
```
And change `setResponseOfPath` in `MockWebServer` like this:
```php
/**
     * Set a specified path to provide a specific response
     *
     * @param string $path
     * @param \donatj\MockWebServer\ResponseInterface $response
     * @param string $method HTTP method
     * @return string
     */
	public function setResponseOfPath( $path, ResponseInterface $response, $method = 'GET' ) {
	    $path = $path . '.' . $method;
		$ref = InternalServer::storeResponse($this->tmpDir, $response);

		$aliasPath = InternalServer::aliasPath($this->tmpDir, $path);

		if( !file_put_contents($aliasPath, $ref) ) {
			throw new \RuntimeException('Failed to store path alias');
		}

		return $this->getServerRoot() . $path;
	}
```
Now this functional available:
```php
$this->_server->setResponseOfPath(
                '/tasks',
                new Response(
                    \yii\helpers\Json::encode(['name' => 'test']),
                    [ 'Cache-Control' => 'no-cache', 'Content-Type' => 'application/json' ],
                    201
                ),
                'POST'
            );
```

**Comment by donatj** [comment]
v2.0.0 is offically released. See the example here: [methods.php](https://github.com/donatj/mock-webserver/blob/0a124a2261fd99463267e82ca9c4eb37fb656cf7/example/methods.php)
