### ISSUE TITLE
Make Default HTTP Response Configurable

### ISSUE THREAD

**Issue by donatj** [donatj/mock-webserver#31]
> It would be very helpful. Having HTTP 200 responses when something is not mocked is not ideal.

_Originally posted by @itsjavi in https://github.com/donatj/mock-webserver/issues/23#issuecomment-890953710_

**Comment by donatj** [comment]
@itsjavi The feature has been merged, and a release has been tagged! 

https://github.com/donatj/mock-webserver/releases/tag/v2.4.0

**Comment by itsjavi** [comment]
that's cool, thank u!
