### ISSUE TITLE
Fix JsonSerializable deprecation in PHP 8.1

### ISSUE THREAD

**Issue by ArondeParon** [donatj/mock-webserver#36]
As mentioned (and fixed) in https://github.com/donatj/mock-webserver/commit/1fde5ecb816ca05465eef1a258129b35e5dd369a, the `JsonSerializable` interface signature has changed in PHP 8.1.

A fix has already been implemented for this several months ago, but it has not been released yet.

Since PHP 8.1 has now been released, it would be really great if a new release can be drafted with PHP 8.1 support.

**Comment by donatj** [comment]
Sorry about that, I was waiting for some other changes to materialize and I just never found the time.

I've pushed a tag -

https://github.com/donatj/mock-webserver/releases/tag/v2.4.1

**Comment by ArondeParon** [comment]
No problem, thanks for releasing a new version!
