### ISSUE TITLE
TypeError : fclose(): supplied resource is not a valid stream resource

### ISSUE THREAD

**Issue by cgimenes** [donatj/mock-webserver#67]
I don't think `@fclose($descriptor);` at `src/MockWebServer.php#L135` is working.
Maybe wrap in an empty try/catch?

**Comment by cgimenes** [comment]
What do you think of? https://github.com/donatj/mock-webserver/pull/68

**Comment by donatj** [comment]
Can you provide a code example of how to trigger the issue?

**Comment by cgimenes** [comment]
Just to be clear. I was using 2.6.1 and after upgrading to 2.7.1 I started getting `TypeError : fclose(): supplied resource is not a valid stream resource` when calling `MockWebServer->stop()`

**Comment by donatj** [comment]
I can't come up with any way that that a descriptor should be in that array and not _open_. 

Are you using any sort of test parallelizers or such?

**Comment by cgimenes** [comment]
Yes, I'm using. But, I think I may found out why I'm the only one having this issue. I'm calling `stop()` twice.

**Comment by cgimenes** [comment]
```<?php

declare(strict_types=1);

use donatj\MockWebServer\MockWebServer;
use PHPUnit\Framework\TestCase;

class ExampleTest extends TestCase
{
    public function setUp(): void
    {
        $this->server = new MockWebServer();
        $this->server->start();
    }

    public function tearDown(): void
    {
        $this->server->stop();
        $this->server->stop();
    }

    public function testValid(): void
    {
        self::assertTrue(true);
    }
}```

**Comment by donatj** [comment]
You know, that's the one thing I didn't think of. That would do it. I will fix that!

**Comment by donatj** [comment]
Published a release with a fix and a regression test ;)

Thanks for the report!

https://github.com/donatj/mock-webserver/releases/tag/v2.7.2

**Comment by cgimenes** [comment]
Thank you!
