### ISSUE TITLE
Server start blocks

### ISSUE THREAD

**Issue by lajthabalazs** [donatj/mock-webserver#7]
This was just the library I was looking for to test out a HTTP client layer I was writing for an application. Enabled sockets extension in php.ini (running PHP version 7.2.1 on Windows), and added mock-webserver with composer as indicated.

I was following the PHPUnit example, wrote the following "test" to check out the server:

```
<?php
/**
 * Created by PhpStorm.
 * User: lajtha
 * Date: 2018-02-10
 * Time: 07:34
 */

namespace Test\Client\HTTP;

use donatj\MockWebServer\MockWebServer;
use PHPUnit\Framework\TestCase;

class HTTPClientImplTest extends TestCase
{
    protected static $server;

    public static function setUpBeforeClass()
    {
        print ("Starting server.\n");
        self::$server = new MockWebServer(8084);
        self::$server->start();
        print ("Server started.\n");
    }

    public function testSimpleGet()
    {
        print ("Waiting a bit. \n");
        sleep(120);
        print ("No more waiting.\n");
    }

    public static function tearDownAfterClass()/* The :void return type declaration that should be here would cause a BC issue */
    {
        print ("Server stopping.\n");
        self::$server->stop();
        print ("Server stopped.\n");
    }
}
```
I expect the output to be:

Starting server.
Server started.
Waiting a bit.
No more waiting.
Server stopping.
Server stopped.

But just get:
Starting server.

The server starts up, and is operational, but doesn't run the tests. Tried from the command line and from PhpStorms too. I don't have much experience with PHP, tried to add some threading but found that it's not as easy as in Java. How could I make the test work?
Thanks, Balázs

**Comment by donatj** [comment]
I am sorry, I should add a note. This is not currently tested nor supported in Windows I am afraid.

The way it is currently implemented is highly dependent on Unix-like shells ability to pipe and control forked processes; something I am woefully unfamiliar with in Windows.

**Comment by donatj** [comment]
I have added a note [here](https://github.com/donatj/mock-webserver/tree/8ca4113e144a9437fa00c876a68fb9d91ddc4533#limitations).

Sorry for the inconvenience.

**Comment by donatj** [comment]
This should be fixed in the next major release. See #15 ( thanks to: #13 )
